---
name: scheduler
description: A new Flutter package project.
version: 0.0.1
homepage: null
environment:
  sdk: '>=2.12.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  uuid: ^3.0.7
  dotted_decoration: ^2.0.0
  dart_date: ^1.1.0
  list_ext: ^1.0.4
  responsive_framework: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.8.1
flutter: null
