---
name: scheduler
description: A new Flutter package project.
version: 0.0.1
homepage: null
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  uuid: ^3.0.7
  dotted_decoration: ^2.0.0
  dart_date: ^1.2.2
  list_ext: ^1.0.6
  responsive_framework: ^1.1.0
  another_transformer_page_view: ^2.0.1
  resizable_widget: ^1.0.5
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.5
flutter: null
