---
name: scheduler
description: A new Flutter package project.
version: 0.0.1
homepage: null
environment:
  sdk: '>=2.17.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  uuid: ^3.0.7
  dotted_decoration: ^2.0.0
  dart_date: ^1.2.1
  list_ext: ^1.0.6
  responsive_framework: ^1.0.0
  another_transformer_page_view: ^2.0.1
  resizable_widget: ^1.0.5
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.3
flutter: null
